### ISSUE TITLE
Unable to pull all 137 policies

### ISSUE THREAD

**Issue by TheGrumpyTechnician** [Kvikku/IntuneAssignments#16]
The policy section only pulls around 30 policies and not all 137 that are for Windows 10 and later. Is this normal behavior?

The permissions on the App Registration are all correct and I was able to connect up using my Admin credentials.

**Comment by Kvikku** [comment]
Hi and thank you for raising an issue!

This is not normal behaviour, and I've seen similar issues with a large number of policies on my end. 

I will look into it ASAP and get back to you!

**Comment by TheGrumpyTechnician** [comment]
Thank you for responding so quickly! 

Definitely let me know if you have any updates or want me to test.

**Comment by Kvikku** [comment]
Apoligize for the delay - I've been sick for some time.

In the newest version which released today I believe I've fixed the issue you've encountered. Please upgrade to it and try again, and do let me know if that fixed the issue or not!

[](https://github.com/Kvikku/IntuneAssignments/releases/tag/0.2.6-beta)

**Comment by TheGrumpyTechnician** [comment]
No worries I hope you feel better!

Awesome, thank you for taking the time to fix it! im having a hard time finding the update package. where is it? and how do I update it?

**Comment by Kvikku** [comment]
Thank you - I feel much better =)

You will find the new version here - https://github.com/Kvikku/IntuneAssignments/releases

To upgrade you simply run the installer for the newest version (0.2.6-beta). You should not have to remove the previous version from your computer. The installer will simply install the newest version and remove others automatically.

**Comment by TheGrumpyTechnician** [comment]
Hey there! i updated it and still the same issue. its like theres another page and I can't get to it. take a look

One is the app and the other is my intune portal showing the other portion of CIS policies. its around 80 ish policies. and I can only see around 20-30 of them thats on the first "page"

![Image](https://github.com/user-attachments/assets/75e56521-cb48-4a94-82b8-c907f3879c46)
![Image](https://github.com/user-attachments/assets/50962054-8c8a-4045-9df3-93753747b420)

**Comment by TheGrumpyTechnician** [comment]
Interesting enough, the app doesn't even show the rest of the 3.11 policies. so it doens't see it at all then...very odd. 

![Image](https://github.com/user-attachments/assets/6d7ba856-a080-452e-a0d1-18c22af2c274)

**Comment by TheGrumpyTechnician** [comment]
adding more fuel to the fire sorry.

Cant assign whats there to a group

![Image](https://github.com/user-attachments/assets/89c71518-238b-43db-bef5-c56def801b4f)



See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Microsoft.Graph.Beta.Models.ODataErrors.ODataError: {
  "_version": 3,
  "Message": "Invalid GroupId : fa1419af-eaee-44cf-8708-47b4702c26db_61941f55-3feb-4159-b593-c92aa93c9930 provided, a valid AADGroupId is expected. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 1c70021c-ffe9-4e6e-b882-fbeb5703cdaa - Url: https://fef.msua06.manage.microsoft.com/DeviceConfigV2/DCV2GraphService/de147310-ffff-8021-0607-031404064602/deviceManagement/configurationPolicies('9606f054-5256-41d8-bd5e-2a1947155f75')/microsoft.management.services.api.assign?api-version=5024-12-01",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Beta.DeviceManagement.ConfigurationPolicies.Item.Assign.AssignRequestBuilder.PostAsync(AssignPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at IntuneAssignments.Policy.AssignSettingsCatalog(String policyID, String groupID)
   at IntuneAssignments.Policy.AssignSelectedPolicies()
   at IntuneAssignments.Policy.btnDeployPolicyAssignment_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Private.CoreLib.dll
----------------------------------------
IntuneAssignments
    Assembly Version: 1.0.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\IntuneAssignments.dll
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.13\System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.13\System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Runtime.InteropServices.dll
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Collections.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.13\System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.13\Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.13\System.Resources.Extensions.dll
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Memory.dll
----------------------------------------
System.Drawing
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.13\System.Drawing.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Collections.Concurrent.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.ObjectModel.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.13\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Linq.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Extensions.Configuration.Abstractions.dll
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly Version: 8.0.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Extensions.Configuration.dll
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly Version: 8.0.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Extensions.Configuration.Json.dll
----------------------------------------
Microsoft.Kiota.Abstractions
    Assembly Version: 1.9.1.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Kiota.Abstractions.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Private.Uri.dll
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Extensions.FileProviders.Abstractions.dll
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Extensions.Configuration.FileExtensions.dll
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 8.0.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Extensions.FileProviders.Physical.dll
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Extensions.Primitives.dll
----------------------------------------
System.Text.Json
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Text.Json.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Text.Encoding.Extensions.dll
----------------------------------------
Microsoft.Graph.Beta
    Assembly Version: 5.78.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Graph.Beta.dll
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 3.1.12.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Graph.Core.dll
----------------------------------------
System.Console
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Console.dll
----------------------------------------
System.Net.Http
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Net.Primitives.dll
----------------------------------------
Microsoft.Kiota.Http.HttpClientLibrary
    Assembly Version: 1.4.3.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Kiota.Http.HttpClientLibrary.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Text.RegularExpressions.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Reflection.Primitives.dll
----------------------------------------
Microsoft.Kiota.Serialization.Json
    Assembly Version: 1.3.3.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Kiota.Serialization.Json.dll
----------------------------------------
Microsoft.Kiota.Serialization.Text
    Assembly Version: 1.2.2.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Kiota.Serialization.Text.dll
----------------------------------------
Microsoft.Kiota.Serialization.Form
    Assembly Version: 1.2.4.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Kiota.Serialization.Form.dll
----------------------------------------
Microsoft.Kiota.Serialization.Multipart
    Assembly Version: 1.1.5.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Kiota.Serialization.Multipart.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Runtime.Intrinsics.dll
----------------------------------------
Std.UriTemplate
    Assembly Version: 1.0.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Std.UriTemplate.dll
----------------------------------------
Microsoft.Identity.Client
    Assembly Version: 4.61.3.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.Identity.Client.dll
----------------------------------------
Microsoft.IdentityModel.Abstractions
    Assembly Version: 7.6.0.0
    Location: C:\Program Files (x86)\SundetCorp\Intune Assignment Installer\Microsoft.IdentityModel.Abstractions.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Collections.Immutable.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Reflection.Metadata.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Net.Security
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Security.Cryptography.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Security.Claims.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Net.HttpListener
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Net.HttpListener.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Diagnostics.Process.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Net.WebHeaderCollection.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Net.Requests.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.IO.Compression.dll
----------------------------------------
System.Threading.Channels
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Threading.Channels.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.13\System.IO.MemoryMappedFiles.dll
----------------------------------------

************** JIT Debugging **************

**Comment by Kvikku** [comment]
Hi again,

This is interesting. Thank you for the pictures and explanation. I will look into it asap. Will try to mirror your setup and create a ton of dummy policies to see if I can replicate and fix it. 

I'll get back to you as fast as I can!
